# Generated by Django 5.1.3 on 2024-11-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cottage_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='base_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cottage',
            name='base_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='capacity',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
